openapi: 3.0.0
info:
  title: Fastcash API
  description: Payment Methods Endpoints
  version: "10"
  contact:
    email: dev@fastcash.com.br
servers:
  - url: "https://www.fastcash.com.br/apiv10Sandbox"
    description: Desenvolvimento
paths:
  /paymentmethod:
    get:
      tags:
        - Payment Methods
      operationId: GetPaymentMethods
      parameters:
        - name: bankNumber
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPaymentMethodsReply"
              examples:
                schame:
                  $ref: "#/components/examples/GetPaymentMethodsReply"
  /transaction/paymentmethods:
    get:
      tags:
        - Payment Methods
      operationId: GetOnlyPaymentMethods
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOnlyPaymentMethodsReply"
              examples:
                schame:
                  $ref: "#/components/examples/GetOnlyPaymentMethodsReply"
  /transaction/subpaymentmethods/{paymentMethodId}:
    get:
      tags:
        - Payment Methods
      operationId: GetSubPaymentMethods
      parameters:
        - name: paymentMethodId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSubPaymentMethodsReply"
              examples:
                schame:
                  $ref: "#/components/examples/GetSubPaymentMethodsReply"
components:
  schemas:
    BaseRequest:
      allOf:
        - $ref: "#/components/schemas/CompanyConfiguration"
    BaseReply:
      properties:
        Success:
          type: boolean
        Message:
          type: string
        StatusCode:
          format: int32
          type: integer
    CompanyConfiguration:
      properties:
        Pid:
          type: integer
          format: int32
        ProdId:
          type: integer
          format: int32
      required:
        - Pid
        - ProdId
    PaymentMethod:
      type: object
      properties:
        Id:
          format: int32
          type: integer
        Name:
          type: string
        Description:
          type: string
        Icon:
          type: string
        Descricao:
          type: string
        Icone:
          type: string
    SubPaymentMethod:
      type: object
      properties:
        Id:
          format: int32
          type: integer
        Name:
          type: string
        Description:
          type: string
        Icon:
          type: string
        BankNumber:
          type: string
        Descricao:
          type: string
        Icone:
          type: string
    GetPaymentMethodsReply:
      allOf:
        - $ref: "#/components/schemas/BaseReply"
      properties:
        Result:
          type: array
          items:
            type: object
            properties:
              PaymentMethod:
                $ref: "#/components/schemas/PaymentMethod"
              SubPaymentMethods:
                type: array
                items:
                  $ref: "#/components/schemas/SubPaymentMethod"
    GetOnlyPaymentMethodsReply:
      allOf:
        - $ref: "#/components/schemas/BaseReply"
      properties:
        Result:
          type: array
          items:
            $ref: "#/components/schemas/PaymentMethod"
    GetSubPaymentMethodsReply:
      allOf:
        - $ref: "#/components/schemas/BaseReply"
      properties:
        Result:
          type: array
          items:
            $ref: "#/components/schemas/SubPaymentMethod"
  examples:
    GetPaymentMethodsReply:
      summary: OK
      value: |
        {
            "Result": [
                {
                    "PaymentMethod": {
                        "Id": 1,
                        "Name": "Depósito",
                        "Description": null,
                        "Icon": null,
                        "Descricao": null,
                        "Icone": null
                    },
                    "SubPaymentMethods": [
                        {
                            "Id": 1,
                            "Name": "Banco do Brasil",
                            "Description": null,
                            "Icon": "https://www.fastcash.com.br/imagens/mailing/bb.png",
                            "BankNumber": "001",
                            "Descricao": null,
                            "Icone": "https://www.fastcash.com.br/imagens/mailing/bb.png"
                        }
                    ]
                }
            ],
            "Success": true,
            "Message": null,
            "StatusCode": 200
        }
    GetOnlyPaymentMethodsReply:
      summary: OK
      value: |
        {
          "Result": [
            {
              "Id": 1,
              "Name": "Depósito",
              "Description": null,
              "Icon": null,
              "Descricao": null,
              "Icone": null
            },
            {
              "Id": 2,
              "Name": "Transferência",
              "Description": null,
              "Icon": null,
              "Descricao": null,
              "Icone": null
            }
          ],
          "Success": true,
          "Message": null,
          "StatusCode": 200
        }
    GetSubPaymentMethodsReply:
      summary: OK
      value: |
        {
          "Result": [
            {
              "Id": 4,
              "Name": "Itaú",
              "Description": null,
              "Icon": "https://www.fastcash.com.br/imagens/mailing/itau.png",
              "BankNumber": "341",
              "Descricao": null,
              "Icone": "https://www.fastcash.com.br/imagens/mailing/itau.png"
            },
            {
              "Id": 2,
              "Name": "Bradesco",
              "Description": null,
              "Icon": "https://www.fastcash.com.br/imagens/mailing/bdn.png",
              "BankNumber": "237",
              "Descricao": null,
              "Icone": "https://www.fastcash.com.br/imagens/mailing/bdn.png"
            }
          ],
          "Success": true,
          "Message": null,
          "StatusCode": 200
        }
tags:
  - name: Payment Methods
    description: ""
