openapi: 3.0.1
info:
  title: PIX INDIRECT
  version: v1
servers:
  - url: "https://www.fastcash.com.br/apiv10Sandbox"
paths:
  /pix/v1/dict/keys:
    post:
      tags:
        - Dict
      summary: Create a PIX Key
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePixDictKeyRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CreatePixDictKeyRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreatePixDictKeyRequest'
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/CreatePixDictKeyReply'
    delete:
      tags:
        - Dict
      summary: Delete a PIX Key
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePixDictKeyRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/DeletePixDictKeyRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DeletePixDictKeyRequest'
      responses:
        '204':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/DeletePixDictKeyReply'
    get:
      tags:
        - Dict
      summary: Get a PIX Key
      parameters:
        - name: KeyValue
          in: query
          required: true
          schema:
            type: string
        - name: Pid
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: ProdId
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
            application/json:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
            text/json:
              schema:
                $ref: '#/components/schemas/GetPixDictKeyReply'
components:
  schemas:
    CreatePixDictKeyReply:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
          nullable: true
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        result:
          $ref: '#/components/schemas/CreatePixDictKeyReplyValue'
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/PropertyErrorData'
          nullable: true
      additionalProperties: false
    CreatePixDictKeyReplyValue:
      type: object
      additionalProperties: false
    CreatePixDictKeyRequest:
      required:
        - Key
        - Pid
        - ProdId
      type: object
      properties:
        Pid:
          type: integer
          format: int32
        ProdId:
          type: integer
          format: int32
        Key:
          $ref: '#/components/schemas/KeyDto'
      additionalProperties: false
    DeletePixDictKeyReply:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
          nullable: true
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        result:
          $ref: '#/components/schemas/DeletePixDictKeyReplyValue'
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/PropertyErrorData'
          nullable: true
      additionalProperties: false
    DeletePixDictKeyReplyValue:
      type: object
      additionalProperties: false
    DeletePixDictKeyRequest:
      required:
        - Key
        - Pid
        - ProdId
      type: object
      properties:
        Pid:
          type: integer
          format: int32
        ProdId:
          type: integer
          format: int32
        Key:
          $ref: '#/components/schemas/KeyValueDto'
      additionalProperties: false
    GetPixDictKeyReply:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
          nullable: true
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        result:
          $ref: '#/components/schemas/GetPixDictKeyReply'
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/PropertyErrorData'
          nullable: true
      additionalProperties: false
    HttpStatusCode:
      enum:
        - Continue
        - SwitchingProtocols
        - Processing
        - EarlyHints
        - OK
        - Created
        - Accepted
        - NonAuthoritativeInformation
        - NoContent
        - ResetContent
        - PartialContent
        - MultiStatus
        - AlreadyReported
        - IMUsed
        - MultipleChoices
        - MovedPermanently
        - Found
        - SeeOther
        - NotModified
        - UseProxy
        - Unused
        - TemporaryRedirect
        - PermanentRedirect
        - BadRequest
        - Unauthorized
        - PaymentRequired
        - Forbidden
        - NotFound
        - MethodNotAllowed
        - NotAcceptable
        - ProxyAuthenticationRequired
        - RequestTimeout
        - Conflict
        - Gone
        - LengthRequired
        - PreconditionFailed
        - RequestEntityTooLarge
        - RequestUriTooLong
        - UnsupportedMediaType
        - RequestedRangeNotSatisfiable
        - ExpectationFailed
        - MisdirectedRequest
        - UnprocessableEntity
        - Locked
        - FailedDependency
        - UpgradeRequired
        - PreconditionRequired
        - TooManyRequests
        - RequestHeaderFieldsTooLarge
        - UnavailableForLegalReasons
        - InternalServerError
        - NotImplemented
        - BadGateway
        - ServiceUnavailable
        - GatewayTimeout
        - HttpVersionNotSupported
        - VariantAlsoNegotiates
        - InsufficientStorage
        - LoopDetected
        - NotExtended
        - NetworkAuthenticationRequired
      type: string
    KeyDto:
      required:
        - Type
        - Value
      type: object
      properties:
        Type:
          $ref: '#/components/schemas/KeyType'
        Value:
          type: string
      additionalProperties: false
    KeyType:
      enum:
        - EVP
        - CPF
        - CNPJ
        - EMAIL
        - PHONE
      type: string
    KeyValueDto:
      required:
        - Value
      type: object
      properties:
        Value:
          type: string
      additionalProperties: false
    PropertyErrorData:
      type: object
      properties:
        Code:
          type: integer
          format: int32
          nullable: true
        PropertyName:
          type: string
          nullable: true
        ErrorMessage:
          type: string
          nullable: true
        AttemptedValue:
          nullable: true
      additionalProperties: false
