openapi: 3.0.0
info:
  title: Fastcash Pix - API
  description: Endpoints
  version: '10'
  contact:
    email: dev@fastcash.com.br
servers:
  - url: 'https://dev.meu.cash/apiv10'
    description: Development
paths:
  /pix/v1/receive:
    post:
      description: >
        Creates a cashin pix transaction.
      summary: Create pix transaction
      operationId: CreatePixCashin
      tags:
        - Receive
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePixCashinRequest'
      responses:
        '200':
          description: Pix Transaction Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixCashinReply'
        '400':
          description: Invalid Request
  /pix/v1/location:
      post:
        description: N/A
        summary: Create a PIX Location (Payable URL)
        operationId: CreatePixLocationCashin
        tags:
          - Receive
        requestBody:
          description: > 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixLocationCashinRequest'
        responses:
          '200':
            description: ""
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreatePixLocationCashinReply'
  /pix/v1/location/{id}/unlink:
    put:
      description: N/A
      summary: Unlink a PIX Payable URL from a PIX Transaction
      operationId: UnlinkPixLocation
      tags:
        - Receive
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id to update pix transaction
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnlikPixLocationCashinReply'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
  /pix/v1/qrcode/by-location:
    post:
      description: N/A
      summary: Generate a PIX dynamic qrcode image
      operationId: ShowQRCodePixLocation
      tags:
        - Receive
      requestBody:
        description: >
          Format:
            * `base64`
            * `svg`

          Base64.Type
            * `gif`
            * `png`
            * `jpeg`
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowQRCodePixLocationRequest'
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowQrCodePixCashinReply'
  /pix/v1/qrcode/by-tid:
    post:
      description: N/A
      summary: Generate a PIX dynamic qrcode image
      operationId: ShowQRCodePix
      tags:
        - Receive
      requestBody:
        description: >
            Format:
             * `base64`
             * `svg`

            Base64.Type
              * `gif`
              * `png`
              * `jpeg`
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowQRCodePixRequest'
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowQrCodePixCashinReply'
  /pix/v1/refund:
    post:
      description: N/A
      summary: Refund a received PIX transaction
      operationId: PixRefund
      tags:
        - Receive
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PixRefundRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PixRefundReply'
  /pix/v1/consult/refunds/tid/{tid}:
    get:
      description: N/A
      summary: List the PIX Refunds issued for a pix transaction
      operationId: PixRefunds
      tags:
        - Receive
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PixRefundsReply'
  /pix/v1/consult/tid/{tid}:
    get:
      description: N/A
      summary: Query a PIX transaction
      operationId: GetPixTransaction
      tags:
        - Receive
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPixCashinReply'
  /pix/v1/send:
    post:
      description: >
        Send a PIX Payment.
      summary: Send a PIX Payment
      operationId: SendPixTransaction
      tags:
        - Receive
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendPixReply'
  /pix/v1/send/initiate:
    post:
      description: Initiate a send pix operation (POS)
      summary: Initiate a send pix operation (POS)
      operationId: InitiateSendPixTransaction
      tags:
        - Receive
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateSendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateSendPixReply'
  /pix/v1/send/confirm:
    post:
      description: Confirm an initiated send pix operation (POS)
      summary: Confirm an initiated send pix operation (POS)
      operationId: ConfirmSendPixTransaction
      tags:
        - Receive
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmSendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmSendPixReply'
  /pix/v1/qrcode/parse:
    post:
      description: Parse a QR code EMV (pix qrcode content) 
      summary: Parse a QR code EMV (pix qrcode content)
      operationId: QrCodePardePixTransaction
      tags:
        - Receive
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QrCodeParsePixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrCodeParsePixReply'
  /pix/v1/send/consult/tid/{tid}:
    get:
      description: N/A
      summary: Query a Send PIX transaction
      operationId: ConsultSendPixTransaction
      tags:
        - Receive
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultSendPixReply'
components:
  schemas:
    TransactionStatus:
      properties:
        Status:
          type: integer
        StatusName:
          type: string
    TransactionParameter:
      properties:
        Id:
          type: string
        Name:
          type: string
        Value:
          type: string
    Transaction:
      properties:
        Tid:
          type: string
        Pid:
          type: integer
        ProdId:
          type: integer
        Custom:
          type: string
        Amount:
          type: number
        Description:
          type: string
        PaymentMethod:
          type: integer
        SubPaymentMethod:
          type: integer
    Customer:
      properties:
        Document:
          type: string
        Name:
          type: string
        Email:
          type: string
        MobilePhone:
          type: string
    PixTransaction:
      allOf:
        - $ref: '#/components/schemas/RequestType'
        - $ref: '#/components/schemas/Location'
      properties:
        Instructions:
          type: string
        FixedAmount:
          type: boolean
        OnDemand:
          $ref: '#/components/schemas/OnDemand' 
        Scheduled:
          $ref: '#/components/schemas/Scheduled' 
    SendTransactionWithBankAccount:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinRequest'
      properties:
        RemittanceInformation:
          type: string
        Destinatary:
         $ref: '#/components/schemas/DestinataryWithBankAccount'
        Schedule:
         $ref: '#/components/schemas/Schedule'
    SendTransaction:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinRequest'
      properties:
        RemittanceInformation:
          type: string
        Destinatary:
         $ref: '#/components/schemas/Destinatary'
        Schedule:
         $ref: '#/components/schemas/Schedule'
    RequestType:
      properties:
        RequestType:
          type: string
          enum:             
            - OnDemand
            - Scheduled
          description: >
            Sort order:
             * `OnDemand` - OnDemand
             * `Scheduled` - Scheduled
    Location:
      properties:
        Location:
          properties:
            Id:
              type: string
              format: uuid
            Location:
              type: string
    Destinatary:
      properties:
        DictKey:
          type: string
        Emv:
          type: string
    DestinataryWithBankAccount:
      allOf:
        - $ref: '#/components/schemas/Destinatary'
      properties:
        BankAccount:
          $ref: '#/components/schemas/BankAccountInfo'
    BankAccountInfo:
      properties:
        BankNumber:
          type: string
        BranchNumber:
          type: string
        AccountNumber:
          type: string
        AccountType:
          type: string
        HolderName:
          type: string
        HolderDocument:
          type: string
    Schedule:
      properties:
        SendAt:
          type: string
          format: date-time
    Image:
      properties:
        Image:
          properties:
            Data:
              type: string
              format: byte
            Format:
              type: string
    Base64Image:
      properties:
        Type:
          type: string
          enum:
            - gif
            - png
            - jpeg
    OnDemand:
      properties:
        Ttl:
          type: number
          description: In seconds
    Scheduled:
      properties:
        DueDate:
          type: string
        OverdueLimit:
          type: number
          description: Limits in days
    Refund:
      properties:
        RefundId:
          type: number
        RefundDate:
          type: string
        RefundAmount:
          type: number
        Status:
          type: number
        StatusName:
          type: string
    Error:
     properties:
        PropertyName:
          type: string
        ErrorMessage:
          type: string
        AttemptedValue:
          type: string
    BaseReply:
      properties:
        Success:
          type: boolean
        Message:
          type: string
        StatusCode:
          type: integer
    BaseCreateCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/Transaction'
                - $ref: '#/components/schemas/TransactionStatus'
                - $ref: '#/components/schemas/PixTransaction'
              properties:
                EMV:
                  type: string
            Parameters:
              type: array
              items:
                $ref: '#/components/schemas/TransactionParameter'
    BaseCreatePixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          allOf:
            - $ref: '#/components/schemas/Location'
    BaseShowQrCodePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          allOf:
            - $ref: '#/components/schemas/Image'
    BaseRequest:
      properties:
        Pid:
          type: integer
        ProdId:
          type: integer
    BaseCreateCashinRequest:
      allOf:
        - $ref: '#/components/schemas/BaseRequest'
      properties:
        Tid:
          type: string
        Custom:
          type: string
        Amount:
          type: number
        Description:
          type: string     
    CreatePixLocationCashinRequest:
      allOf:
        - $ref: '#/components/schemas/RequestType'
    CreatePixCashinRequest:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinRequest'
        - $ref: '#/components/schemas/PixTransaction'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    SendPixRequest:
      allOf:
        - $ref: '#/components/schemas/SendTransactionWithBankAccount'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    InitiateSendPixRequest:
      allOf:
        - $ref: '#/components/schemas/SendTransaction'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    ConfirmSendPixRequest:
      properties:
        Pid:
          type: number
        Tid:
          type: string
        Amount:
          type: number
        RemittanceInformation:
          type: string
    ShowQRCodePixRequest:
      properties:
        Format:
          type: string
          enum:             
            - base64
            - svg 
        Tid:
          type: string
        Pid:
          type: number
          format: int32
        Sizepx:
          type: number
          format: int32
        Base64:
          $ref: '#/components/schemas/Base64Image'
    ShowQRCodePixLocationRequest:
      properties:
        Format:
          type: string
          enum:             
            - base64
            - svg
        LocationId:
          type: string
        Sizepx:
          type: number
          format: int32
        Base64:
          $ref: '#/components/schemas/Base64Image'
    QrCodeParsePixRequest:
      properties:
        EMV:
          type: string
    CreatePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinReply'
    CreatePixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreatePixLocationCashinReply'
    UnlikPixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreatePixLocationCashinReply'
    ShowQrCodePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseShowQrCodePixCashinReply'
    PixRefundRequest:
      properties:
        Tid:
          type: string
        Pid:
          type: integer
        Amount:
          type: number
    PixRefundReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
    PixRefundsReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Tid:
              type: string
            Pid:
              type: integer
            Refunds:
              items:
                $ref: '#/components/schemas/Refund'
    GetPixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/Transaction'
                - $ref: '#/components/schemas/TransactionStatus'
                - $ref: '#/components/schemas/PixTransaction'
            Parameters:
              type: array
              items:
                $ref: '#/components/schemas/TransactionParameter'
    SendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransactionWithBankAccount'
              properties:
                Status:
                  type: number
    InitiateSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransaction'
              properties:
                Status:
                  type: number
    ConfirmSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    QrCodeParsePixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          type: string
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    ConsultSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransactionWithBankAccount'
              properties:
                Status:
                  type: number
tags:
  - name: pix
    description: PIX Transactions