openapi: 3.0.0
info:
  title: Fastcash Pix - API
  description: Endpoints
  version: '10'
  contact:
    email: dev@fastcash.com.br
servers:
  - url: 'https://dev.meu.cash/apiv10'
    description: Desenvolvimento
paths:
  /pix/v1/receive:
    post:
      description: >
        Creates a cashin pix transaction.
      summary: Create pix transaction
      operationId: CreatePixCashin
      tags:
        - pix
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePixCashinRequest'
      responses:
        '200':
          description: Pix Transaction Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixCashinReply'
        '400':
          description: Invalid Request
  /pix/v1/location:
      post:
        description: N/A
        summary: Create a PIX Location (Payable URL)
        operationId: CreatePixLocationCashin
        tags:
          - pix
        requestBody:
          description: > 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePixLocationCashinRequest'
        responses:
          '200':
            description: ""
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreatePixLocationCashinReply'
  /pix/v1/location/{id}/unlink:
    post:
      description: N/A
      summary: Unlink a PIX Payable URL from a PIX Transaction
      operationId: UnlinkPixLocation
      tags:
        - pix
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id to update pix transaction
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnlikPixLocationCashinReply'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
  /pix/v1/qrcode/generate/{format}/{locationId}:
    get:
      description: N/A
      summary: Generate a PIX dynamic qrcode image
      operationId: ShowQRCodePixLocation
      tags:
        - pix
      parameters:
        - in: path
          name: format
          schema:
            type: string
          required: true
          description: N/A
        - in: path
          name: locationId
          schema:
            type: string
          required: true
          description: N/A
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowQrCodePixCashinReply'
  /pix/v1/qrcode/generate/{format}/pid/{pid}/tid/{tid}:
    get:
      description: N/A
      summary: Generate a PIX dynamic qrcode image
      operationId: ShowQRCodePix
      tags:
        - pix
      parameters:
        - in: path
          name: format
          schema:
            type: string
          required: true
          description: N/A
        - in: path
          name: pid
          schema:
            type: number
          required: true
          description: N/A
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
      responses:
        '200':
          description: N/A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowQrCodePixCashinReply'
  /pix/v1/refund:
    post:
      description: N/A
      summary: Refund a received PIX transaction
      operationId: PixRefund
      tags:
        - pix
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PixRefundRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PixRefundReply'
  /pix/v1/consult/refunds/pid/{pid}/tid/{tid}:
    get:
      description: N/A
      summary: List the PIX Refunds issued for a pix transaction
      operationId: PixRefunds
      tags:
        - pix
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
        - in: path
          name: pid
          schema:
            type: number
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PixRefundsReply'
  /pix/v1/consult/pid/{pid}/tid/{tid}:
    get:
      description: N/A
      summary: Query a PIX transaction
      operationId: GetPixTransaction
      tags:
        - pix
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
        - in: path
          name: pid
          schema:
            type: number
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPixCashinReply'
  /pix/v1/send:
    post:
      description: N/A
      summary: N/A
      operationId: SendPixTransaction
      tags:
        - pix
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendPixReply'
  /pix/v1/initiate-send:
    post:
      description: N/A
      summary: N/A
      operationId: InitiateSendPixTransaction
      tags:
        - pix
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateSendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateSendPixReply'
  /pix/v1/confirm-send:
    post:
      description: N/A
      summary: N/A
      operationId: ConfirmSendPixTransaction
      tags:
        - pix
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmSendPixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmSendPixReply'
  /pix/v1/qrcode/parse:
    post:
      description: N/A
      summary: N/A
      operationId: QrCodePardePixTransaction
      tags:
        - pix
      requestBody:
        description: > 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QrCodeParsePixRequest'
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrCodeParsePixReply'
  /pix/v1/send/consult/pid/{pid}/tid/{tid}:
    get:
      description: N/A
      summary: Query a Send PIX transaction
      operationId: ConsultSendPixTransaction
      tags:
        - pix
      parameters:
        - in: path
          name: tid
          schema:
            type: string
          required: true
          description: N/A
        - in: path
          name: pid
          schema:
            type: number
          required: true
          description: N/A
      responses:
        '200':
          description: Pix Transaction found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultSendPixReply'
components:
  schemas:
    BaseReply:
      properties:
        Success:
          type: boolean
        Message:
          type: string
        StatusCode:
          type: integer
    BaseCreateCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/Transaction'
                - $ref: '#/components/schemas/TransactionStatus'
                - $ref: '#/components/schemas/PixTransaction'
            Parameters:
              type: array
              items:
                $ref: '#/components/schemas/TransactionParameter'
    BaseCreatePixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          allOf:
            - $ref: '#/components/schemas/LocationEntity'
    BaseShowQrCodePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          allOf:
            - $ref: '#/components/schemas/ImageEntity'
    BaseRequest:
      properties:
        Pid:
          type: integer
        ProdId:
          type: integer
    TransactionStatus:
      properties:
        Status:
          type: integer
        StatusName:
          type: string
    BaseCreateCashinRequest:
      allOf:
        - $ref: '#/components/schemas/BaseRequest'
      properties:
        Tid:
          type: string
        Custom:
          type: string
        Amount:
          type: number
        Description:
          type: string
    TransactionParameter:
      properties:
        Id:
          type: string
        Name:
          type: string
        Value:
          type: string
    Transaction:
      properties:
        Tid:
          type: string
        Pid:
          type: integer
        ProdId:
          type: integer
        Custom:
          type: string
        Amount:
          type: number
        Description:
          type: string
        PaymentMethod:
          type: integer
        SubPaymentMethod:
          type: integer
    Customer:
      properties:
        Document:
          type: string
        Name:
          type: string
        Email:
          type: string
        MobilePhone:
          type: string
    PixTransaction:
      allOf:
        - $ref: '#/components/schemas/RequestTypeEntity'
        - $ref: '#/components/schemas/LocationEntity'
      properties:
        Instructions:
          type: string
        FixedAmount:
          type: boolean
        Lifecycle:
          $ref: '#/components/schemas/Lifecycle' 
    SendTransaction:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinRequest'
      properties:
        RemittanceInformation:
          type: string
        Destinatary:
         $ref: '#/components/schemas/DestinataryEntity'
        Schedule:
         $ref: '#/components/schemas/ScheduleEntity'
    RequestTypeEntity:
      properties:
        RequestType:
          type: string
          enum:             
            - Standard
            - DueDate
          description: >
            Sort order:
             * `Standard` - Standard
             * `DueDate` - DueDate
    LocationEntity:
      properties:
        Location:
          properties:
            Id:
              type: string
              format: uuid
            Location:
              type: string
    DestinataryEntity:
      properties:
        DictKey:
          type: string
        Emv:
          type: string
        BankAccount:
          $ref: '#/components/schemas/BankAccountEntity'
    BankAccountEntity:
      properties:
        BankNumber:
          type: string
        BranchNumber:
          type: string
        AccountNumber:
          type: string
        AccountType:
          type: string
        HolderName:
          type: string
        HolderDocument:
          type: string
    ScheduleEntity:
      properties:
        SendAt:
          type: string
          format: date-time
    ImageEntity:
      properties:
        Image:
          properties:
            Data:
              type: string
              format: byte
            Format:
              type: string
    Lifecycle:
      properties:
        Ttl:
          type: number
          description: In seconds
        DueDate:
          type: string
        OverdueLimit:
          type: number
          description: Limits in days
    Refund:
      properties:
        RefundId:
          type: number
        RefundDate:
          type: string
        RefundAmount:
          type: number
        Status:
          type: number
        StatusName:
          type: string
    Error:
      properties:
        PropertyName:
          type: string
        ErrorMessage:
          type: string
        AttemptedValue:
          type: string
    CreatePixLocationCashinRequest:
      allOf:
        - $ref: '#/components/schemas/RequestTypeEntity'
    CreatePixCashinRequest:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinRequest'
        - $ref: '#/components/schemas/PixTransaction'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    SendPixRequest:
      allOf:
        - $ref: '#/components/schemas/SendTransaction'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    InitiateSendPixRequest:
      allOf:
        - $ref: '#/components/schemas/SendTransaction'
      properties:
        Customer:
          $ref: '#/components/schemas/Customer'
    ConfirmSendPixRequest:
      properties:
        Pid:
          type: number
        Tid:
          type: string
    QrCodeParsePixRequest:
      properties:
        EMV:
          type: string
    CreatePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreateCashinReply'
    CreatePixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreatePixLocationCashinReply'
    UnlikPixLocationCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseCreatePixLocationCashinReply'
    ShowQrCodePixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseShowQrCodePixCashinReply'
    PixRefundRequest:
      properties:
        Tid:
          type: string
        Pid:
          type: integer
        Amount:
          type: number
    PixRefundReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
    PixRefundsReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Tid:
              type: string
            Pid:
              type: integer
            Refunds:
              items:
                $ref: '#/components/schemas/Refund'
    GetPixCashinReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/Transaction'
                - $ref: '#/components/schemas/TransactionStatus'
                - $ref: '#/components/schemas/PixTransaction'
            Parameters:
              type: array
              items:
                $ref: '#/components/schemas/TransactionParameter'
    SendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransaction'
              properties:
                Status:
                  type: number
    InitiateSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransaction'
              properties:
                Status:
                  type: number
    ConfirmSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    QrCodeParsePixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Result:
          type: string
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    ConsultSendPixReply:
      allOf:
        - $ref: '#/components/schemas/BaseReply'
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        Result:
          properties:
            Transaction:
              allOf:
                - $ref: '#/components/schemas/SendTransaction'
              properties:
                Status:
                  type: number
tags:
  - name: pix
    description: pix operations